//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesanMakan.Dekstop.PesanMakanServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PesanMakanServices.GetSetServiceSoap")]
    public interface GetSetServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void startService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startService", ReplyAction="*")]
        System.Threading.Tasks.Task startServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startServiceTicketing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string startServiceTicketing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startServiceTicketing", ReplyAction="*")]
        System.Threading.Tasks.Task<string> startServiceTicketingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startServiceDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string startServiceDekstop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startServiceDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> startServiceDekstopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/initCardUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void initCardUID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/initCardUID", ReplyAction="*")]
        System.Threading.Tasks.Task initCardUIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/initCardUIDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string initCardUIDesktop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/initCardUIDesktop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> initCardUIDesktopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetTable(string dateReg, string dateBok, string nik, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        System.Threading.Tasks.Task GetTableAsync(string dateReg, string dateBok, string nik, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SelectDevice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDevice", ReplyAction="*")]
        System.Threading.Tasks.Task SelectDeviceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/btnWrite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void btnWrite(string tbValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/btnWrite", ReplyAction="*")]
        System.Threading.Tasks.Task btnWriteAsync(string tbValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListReaders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ListReaders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListReaders", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ListReadersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/connectCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool connectCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/connectCard", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> connectCardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int submitText(string Text, string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitText", ReplyAction="*")]
        System.Threading.Tasks.Task<int> submitTextAsync(string Text, string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Close", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Close();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Close", ReplyAction="*")]
        System.Threading.Tasks.Task CloseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verifyCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string verifyCard(string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verifyCard", ReplyAction="*")]
        System.Threading.Tasks.Task<string> verifyCardAsync(string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readBlock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string readBlock(string Block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<string> readBlockAsync(string Block);
        
        // CODEGEN: Parameter 'array' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputProses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse InputProses(PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputProses", ReplyAction="*")]
        System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse> InputProsesAsync(PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputProsesFromCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InputProsesFromCalendar(PesanMakan.Dekstop.PesanMakanServices.CalendarEventObj[] listObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputProsesFromCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task InputProsesFromCalendarAsync(PesanMakan.Dekstop.PesanMakanServices.CalendarEventObj[] listObj);
        
        // CODEGEN: Parameter 'array' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse InputMenu(PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse> InputMenuAsync(PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMonthRecap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setMonthRecap(string bulan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMonthRecap", ReplyAction="*")]
        System.Threading.Tasks.Task setMonthRecapAsync(string bulan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setMonth(string bulan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMonth", ReplyAction="*")]
        System.Threading.Tasks.Task setMonthAsync(string bulan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetListOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetListOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenu", ReplyAction="*")]
        System.Threading.Tasks.Task GetMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecapOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RecapOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecapOrder", ReplyAction="*")]
        System.Threading.Tasks.Task RecapOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReconcile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetReconcile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReconcile", ReplyAction="*")]
        System.Threading.Tasks.Task GetReconcileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TotalMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalMember", ReplyAction="*")]
        System.Threading.Tasks.Task TotalMemberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TotalBooking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalBooking", ReplyAction="*")]
        System.Threading.Tasks.Task TotalBookingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalKonfirmasi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TotalKonfirmasi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalKonfirmasi", ReplyAction="*")]
        System.Threading.Tasks.Task TotalKonfirmasiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CheckToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckToken", ReplyAction="*")]
        System.Threading.Tasks.Task CheckTokenAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetUserData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserData", ReplyAction="*")]
        System.Threading.Tasks.Task GetUserDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDataDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserDataDekstop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDataDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUserDataDekstopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSearchDataDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSearchDataDekstop(string nama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSearchDataDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSearchDataDekstopAsync(string nama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DelMenu(string tgl, string menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelMenu", ReplyAction="*")]
        System.Threading.Tasks.Task DelMenuAsync(string tgl, string menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddMenu(string tgl, string menu, string jam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenu", ReplyAction="*")]
        System.Threading.Tasks.Task AddMenuAsync(string tgl, string menu, string jam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CekMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CekMenu(string Period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CekMenu", ReplyAction="*")]
        System.Threading.Tasks.Task CekMenuAsync(string Period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchNik", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SearchNik(string nik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchNik", ReplyAction="*")]
        System.Threading.Tasks.Task SearchNikAsync(string nik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RegCard(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegCard", ReplyAction="*")]
        System.Threading.Tasks.Task RegCardAsync(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegCardDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegCardDekstop(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegCardDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegCardDekstopAsync(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DelData(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelData", ReplyAction="*")]
        System.Threading.Tasks.Task DelDataAsync(string nik, string nama, string cardid, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DelOrder(string tgl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelOrder", ReplyAction="*")]
        System.Threading.Tasks.Task DelOrderAsync(string tgl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithCardUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void loginWithCardUID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithCardUID", ReplyAction="*")]
        System.Threading.Tasks.Task loginWithCardUIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithCardUIDDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string loginWithCardUIDDekstop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithCardUIDDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> loginWithCardUIDDekstopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void loginWithUserName(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithUserName", ReplyAction="*")]
        System.Threading.Tasks.Task loginWithUserNameAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithUserNameDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string loginWithUserNameDekstop(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginWithUserNameDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> loginWithUserNameDekstopAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetMenuBooking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuBooking", ReplyAction="*")]
        System.Threading.Tasks.Task GetMenuBookingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuBookingCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetMenuBookingCalendar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenuBookingCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task GetMenuBookingCalendarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetNikNama();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNama", ReplyAction="*")]
        System.Threading.Tasks.Task GetNikNamaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNikNamaDekstop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNikNamaDekstopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaAct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetNikNamaAct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaAct", ReplyAction="*")]
        System.Threading.Tasks.Task GetNikNamaActAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetResetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResetData", ReplyAction="*")]
        System.Threading.Tasks.Task GetResetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaActDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNikNamaActDesktop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNikNamaActDesktop", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNikNamaActDesktopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RegMember(string nik, string nama, string cardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegMember", ReplyAction="*")]
        System.Threading.Tasks.Task RegMemberAsync(string nik, string nama, string cardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ResetData(string nik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetData", ReplyAction="*")]
        System.Threading.Tasks.Task ResetDataAsync(string nik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByNIK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetUserByNIK(string pernr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByNIK", ReplyAction="*")]
        System.Threading.Tasks.Task GetUserByNIKAsync(string pernr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearSessionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ClearSessionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearSessionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task ClearSessionInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAllSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ClearAllSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAllSession", ReplyAction="*")]
        System.Threading.Tasks.Task ClearAllSessionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenTicketing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetTokenTicketing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenTicketing", ReplyAction="*")]
        System.Threading.Tasks.Task GetTokenTicketingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenTicketingDekstop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTokenTicketingDekstop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenTicketingDekstop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTokenTicketingDekstopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateTimeServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetDateTimeServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateTimeServer", ReplyAction="*")]
        System.Threading.Tasks.Task GetDateTimeServerAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputProses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InputProsesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nik;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] array;
        
        public InputProsesRequest() {
        }
        
        public InputProsesRequest(string nik, string nama, string[][] array) {
            this.nik = nik;
            this.nama = nama;
            this.array = array;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputProsesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InputProsesResponse {
        
        public InputProsesResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CalendarEventObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string titleField;
        
        private string startField;
        
        private string menuField;
        
        private string startHourField;
        
        private string endHourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
                this.RaisePropertyChanged("menu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string startHour {
            get {
                return this.startHourField;
            }
            set {
                this.startHourField = value;
                this.RaisePropertyChanged("startHour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string endHour {
            get {
                return this.endHourField;
            }
            set {
                this.endHourField = value;
                this.RaisePropertyChanged("endHour");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputMenu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InputMenuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] array;
        
        public InputMenuRequest() {
        }
        
        public InputMenuRequest(string[][] array) {
            this.array = array;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputMenuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InputMenuResponse {
        
        public InputMenuResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetSetServiceSoapChannel : PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSetServiceSoapClient : System.ServiceModel.ClientBase<PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap>, PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap {
        
        public GetSetServiceSoapClient() {
        }
        
        public GetSetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void startService() {
            base.Channel.startService();
        }
        
        public System.Threading.Tasks.Task startServiceAsync() {
            return base.Channel.startServiceAsync();
        }
        
        public string startServiceTicketing() {
            return base.Channel.startServiceTicketing();
        }
        
        public System.Threading.Tasks.Task<string> startServiceTicketingAsync() {
            return base.Channel.startServiceTicketingAsync();
        }
        
        public string startServiceDekstop() {
            return base.Channel.startServiceDekstop();
        }
        
        public System.Threading.Tasks.Task<string> startServiceDekstopAsync() {
            return base.Channel.startServiceDekstopAsync();
        }
        
        public void initCardUID() {
            base.Channel.initCardUID();
        }
        
        public System.Threading.Tasks.Task initCardUIDAsync() {
            return base.Channel.initCardUIDAsync();
        }
        
        public string initCardUIDesktop() {
            return base.Channel.initCardUIDesktop();
        }
        
        public System.Threading.Tasks.Task<string> initCardUIDesktopAsync() {
            return base.Channel.initCardUIDesktopAsync();
        }
        
        public void GetTable(string dateReg, string dateBok, string nik, string name) {
            base.Channel.GetTable(dateReg, dateBok, nik, name);
        }
        
        public System.Threading.Tasks.Task GetTableAsync(string dateReg, string dateBok, string nik, string name) {
            return base.Channel.GetTableAsync(dateReg, dateBok, nik, name);
        }
        
        public void SelectDevice() {
            base.Channel.SelectDevice();
        }
        
        public System.Threading.Tasks.Task SelectDeviceAsync() {
            return base.Channel.SelectDeviceAsync();
        }
        
        public void btnWrite(string tbValue) {
            base.Channel.btnWrite(tbValue);
        }
        
        public System.Threading.Tasks.Task btnWriteAsync(string tbValue) {
            return base.Channel.btnWriteAsync(tbValue);
        }
        
        public string[] ListReaders() {
            return base.Channel.ListReaders();
        }
        
        public System.Threading.Tasks.Task<string[]> ListReadersAsync() {
            return base.Channel.ListReadersAsync();
        }
        
        public bool connectCard() {
            return base.Channel.connectCard();
        }
        
        public System.Threading.Tasks.Task<bool> connectCardAsync() {
            return base.Channel.connectCardAsync();
        }
        
        public int submitText(string Text, string Block) {
            return base.Channel.submitText(Text, Block);
        }
        
        public System.Threading.Tasks.Task<int> submitTextAsync(string Text, string Block) {
            return base.Channel.submitTextAsync(Text, Block);
        }
        
        public void Close() {
            base.Channel.Close();
        }
        
        public System.Threading.Tasks.Task CloseAsync() {
            return base.Channel.CloseAsync();
        }
        
        public string verifyCard(string Block) {
            return base.Channel.verifyCard(Block);
        }
        
        public System.Threading.Tasks.Task<string> verifyCardAsync(string Block) {
            return base.Channel.verifyCardAsync(Block);
        }
        
        public string readBlock(string Block) {
            return base.Channel.readBlock(Block);
        }
        
        public System.Threading.Tasks.Task<string> readBlockAsync(string Block) {
            return base.Channel.readBlockAsync(Block);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap.InputProses(PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest request) {
            return base.Channel.InputProses(request);
        }
        
        public void InputProses(string nik, string nama, string[][] array) {
            PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest inValue = new PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest();
            inValue.nik = nik;
            inValue.nama = nama;
            inValue.array = array;
            PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse retVal = ((PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap)(this)).InputProses(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse> PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap.InputProsesAsync(PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest request) {
            return base.Channel.InputProsesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputProsesResponse> InputProsesAsync(string nik, string nama, string[][] array) {
            PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest inValue = new PesanMakan.Dekstop.PesanMakanServices.InputProsesRequest();
            inValue.nik = nik;
            inValue.nama = nama;
            inValue.array = array;
            return ((PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap)(this)).InputProsesAsync(inValue);
        }
        
        public void InputProsesFromCalendar(PesanMakan.Dekstop.PesanMakanServices.CalendarEventObj[] listObj) {
            base.Channel.InputProsesFromCalendar(listObj);
        }
        
        public System.Threading.Tasks.Task InputProsesFromCalendarAsync(PesanMakan.Dekstop.PesanMakanServices.CalendarEventObj[] listObj) {
            return base.Channel.InputProsesFromCalendarAsync(listObj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap.InputMenu(PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest request) {
            return base.Channel.InputMenu(request);
        }
        
        public void InputMenu(string[][] array) {
            PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest inValue = new PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest();
            inValue.array = array;
            PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse retVal = ((PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap)(this)).InputMenu(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse> PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap.InputMenuAsync(PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest request) {
            return base.Channel.InputMenuAsync(request);
        }
        
        public System.Threading.Tasks.Task<PesanMakan.Dekstop.PesanMakanServices.InputMenuResponse> InputMenuAsync(string[][] array) {
            PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest inValue = new PesanMakan.Dekstop.PesanMakanServices.InputMenuRequest();
            inValue.array = array;
            return ((PesanMakan.Dekstop.PesanMakanServices.GetSetServiceSoap)(this)).InputMenuAsync(inValue);
        }
        
        public void setMonthRecap(string bulan) {
            base.Channel.setMonthRecap(bulan);
        }
        
        public System.Threading.Tasks.Task setMonthRecapAsync(string bulan) {
            return base.Channel.setMonthRecapAsync(bulan);
        }
        
        public void setMonth(string bulan) {
            base.Channel.setMonth(bulan);
        }
        
        public System.Threading.Tasks.Task setMonthAsync(string bulan) {
            return base.Channel.setMonthAsync(bulan);
        }
        
        public void GetListOrder() {
            base.Channel.GetListOrder();
        }
        
        public System.Threading.Tasks.Task GetListOrderAsync() {
            return base.Channel.GetListOrderAsync();
        }
        
        public void GetMenu() {
            base.Channel.GetMenu();
        }
        
        public System.Threading.Tasks.Task GetMenuAsync() {
            return base.Channel.GetMenuAsync();
        }
        
        public void RecapOrder() {
            base.Channel.RecapOrder();
        }
        
        public System.Threading.Tasks.Task RecapOrderAsync() {
            return base.Channel.RecapOrderAsync();
        }
        
        public void GetReconcile() {
            base.Channel.GetReconcile();
        }
        
        public System.Threading.Tasks.Task GetReconcileAsync() {
            return base.Channel.GetReconcileAsync();
        }
        
        public void TotalMember() {
            base.Channel.TotalMember();
        }
        
        public System.Threading.Tasks.Task TotalMemberAsync() {
            return base.Channel.TotalMemberAsync();
        }
        
        public void TotalBooking() {
            base.Channel.TotalBooking();
        }
        
        public System.Threading.Tasks.Task TotalBookingAsync() {
            return base.Channel.TotalBookingAsync();
        }
        
        public void TotalKonfirmasi() {
            base.Channel.TotalKonfirmasi();
        }
        
        public System.Threading.Tasks.Task TotalKonfirmasiAsync() {
            return base.Channel.TotalKonfirmasiAsync();
        }
        
        public void CheckToken(string token) {
            base.Channel.CheckToken(token);
        }
        
        public System.Threading.Tasks.Task CheckTokenAsync(string token) {
            return base.Channel.CheckTokenAsync(token);
        }
        
        public void GetUserData() {
            base.Channel.GetUserData();
        }
        
        public System.Threading.Tasks.Task GetUserDataAsync() {
            return base.Channel.GetUserDataAsync();
        }
        
        public System.Data.DataTable GetUserDataDekstop() {
            return base.Channel.GetUserDataDekstop();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUserDataDekstopAsync() {
            return base.Channel.GetUserDataDekstopAsync();
        }
        
        public System.Data.DataTable GetSearchDataDekstop(string nama) {
            return base.Channel.GetSearchDataDekstop(nama);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSearchDataDekstopAsync(string nama) {
            return base.Channel.GetSearchDataDekstopAsync(nama);
        }
        
        public void DelMenu(string tgl, string menu) {
            base.Channel.DelMenu(tgl, menu);
        }
        
        public System.Threading.Tasks.Task DelMenuAsync(string tgl, string menu) {
            return base.Channel.DelMenuAsync(tgl, menu);
        }
        
        public void AddMenu(string tgl, string menu, string jam) {
            base.Channel.AddMenu(tgl, menu, jam);
        }
        
        public System.Threading.Tasks.Task AddMenuAsync(string tgl, string menu, string jam) {
            return base.Channel.AddMenuAsync(tgl, menu, jam);
        }
        
        public void CekMenu(string Period) {
            base.Channel.CekMenu(Period);
        }
        
        public System.Threading.Tasks.Task CekMenuAsync(string Period) {
            return base.Channel.CekMenuAsync(Period);
        }
        
        public void SearchNik(string nik) {
            base.Channel.SearchNik(nik);
        }
        
        public System.Threading.Tasks.Task SearchNikAsync(string nik) {
            return base.Channel.SearchNikAsync(nik);
        }
        
        public void RegCard(string nik, string nama, string cardid, string role) {
            base.Channel.RegCard(nik, nama, cardid, role);
        }
        
        public System.Threading.Tasks.Task RegCardAsync(string nik, string nama, string cardid, string role) {
            return base.Channel.RegCardAsync(nik, nama, cardid, role);
        }
        
        public int RegCardDekstop(string nik, string nama, string cardid, string role) {
            return base.Channel.RegCardDekstop(nik, nama, cardid, role);
        }
        
        public System.Threading.Tasks.Task<int> RegCardDekstopAsync(string nik, string nama, string cardid, string role) {
            return base.Channel.RegCardDekstopAsync(nik, nama, cardid, role);
        }
        
        public void DelData(string nik, string nama, string cardid, string role) {
            base.Channel.DelData(nik, nama, cardid, role);
        }
        
        public System.Threading.Tasks.Task DelDataAsync(string nik, string nama, string cardid, string role) {
            return base.Channel.DelDataAsync(nik, nama, cardid, role);
        }
        
        public void DelOrder(string tgl) {
            base.Channel.DelOrder(tgl);
        }
        
        public System.Threading.Tasks.Task DelOrderAsync(string tgl) {
            return base.Channel.DelOrderAsync(tgl);
        }
        
        public void loginWithCardUID() {
            base.Channel.loginWithCardUID();
        }
        
        public System.Threading.Tasks.Task loginWithCardUIDAsync() {
            return base.Channel.loginWithCardUIDAsync();
        }
        
        public string loginWithCardUIDDekstop() {
            return base.Channel.loginWithCardUIDDekstop();
        }
        
        public System.Threading.Tasks.Task<string> loginWithCardUIDDekstopAsync() {
            return base.Channel.loginWithCardUIDDekstopAsync();
        }
        
        public void loginWithUserName(string username, string pass) {
            base.Channel.loginWithUserName(username, pass);
        }
        
        public System.Threading.Tasks.Task loginWithUserNameAsync(string username, string pass) {
            return base.Channel.loginWithUserNameAsync(username, pass);
        }
        
        public string loginWithUserNameDekstop(string username, string pass) {
            return base.Channel.loginWithUserNameDekstop(username, pass);
        }
        
        public System.Threading.Tasks.Task<string> loginWithUserNameDekstopAsync(string username, string pass) {
            return base.Channel.loginWithUserNameDekstopAsync(username, pass);
        }
        
        public void GetMenuBooking() {
            base.Channel.GetMenuBooking();
        }
        
        public System.Threading.Tasks.Task GetMenuBookingAsync() {
            return base.Channel.GetMenuBookingAsync();
        }
        
        public void GetMenuBookingCalendar() {
            base.Channel.GetMenuBookingCalendar();
        }
        
        public System.Threading.Tasks.Task GetMenuBookingCalendarAsync() {
            return base.Channel.GetMenuBookingCalendarAsync();
        }
        
        public void GetNikNama() {
            base.Channel.GetNikNama();
        }
        
        public System.Threading.Tasks.Task GetNikNamaAsync() {
            return base.Channel.GetNikNamaAsync();
        }
        
        public System.Data.DataTable GetNikNamaDekstop() {
            return base.Channel.GetNikNamaDekstop();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNikNamaDekstopAsync() {
            return base.Channel.GetNikNamaDekstopAsync();
        }
        
        public void GetNikNamaAct() {
            base.Channel.GetNikNamaAct();
        }
        
        public System.Threading.Tasks.Task GetNikNamaActAsync() {
            return base.Channel.GetNikNamaActAsync();
        }
        
        public void GetResetData() {
            base.Channel.GetResetData();
        }
        
        public System.Threading.Tasks.Task GetResetDataAsync() {
            return base.Channel.GetResetDataAsync();
        }
        
        public System.Data.DataTable GetNikNamaActDesktop() {
            return base.Channel.GetNikNamaActDesktop();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNikNamaActDesktopAsync() {
            return base.Channel.GetNikNamaActDesktopAsync();
        }
        
        public void RegMember(string nik, string nama, string cardID) {
            base.Channel.RegMember(nik, nama, cardID);
        }
        
        public System.Threading.Tasks.Task RegMemberAsync(string nik, string nama, string cardID) {
            return base.Channel.RegMemberAsync(nik, nama, cardID);
        }
        
        public void ResetData(string nik) {
            base.Channel.ResetData(nik);
        }
        
        public System.Threading.Tasks.Task ResetDataAsync(string nik) {
            return base.Channel.ResetDataAsync(nik);
        }
        
        public void GetUserByNIK(string pernr) {
            base.Channel.GetUserByNIK(pernr);
        }
        
        public System.Threading.Tasks.Task GetUserByNIKAsync(string pernr) {
            return base.Channel.GetUserByNIKAsync(pernr);
        }
        
        public void ClearSessionInfo() {
            base.Channel.ClearSessionInfo();
        }
        
        public System.Threading.Tasks.Task ClearSessionInfoAsync() {
            return base.Channel.ClearSessionInfoAsync();
        }
        
        public void ClearAllSession() {
            base.Channel.ClearAllSession();
        }
        
        public System.Threading.Tasks.Task ClearAllSessionAsync() {
            return base.Channel.ClearAllSessionAsync();
        }
        
        public void GetTokenTicketing() {
            base.Channel.GetTokenTicketing();
        }
        
        public System.Threading.Tasks.Task GetTokenTicketingAsync() {
            return base.Channel.GetTokenTicketingAsync();
        }
        
        public string GetTokenTicketingDekstop() {
            return base.Channel.GetTokenTicketingDekstop();
        }
        
        public System.Threading.Tasks.Task<string> GetTokenTicketingDekstopAsync() {
            return base.Channel.GetTokenTicketingDekstopAsync();
        }
        
        public void GetDateTimeServer() {
            base.Channel.GetDateTimeServer();
        }
        
        public System.Threading.Tasks.Task GetDateTimeServerAsync() {
            return base.Channel.GetDateTimeServerAsync();
        }
    }
}
